apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: semantic-router-operator-leader-election-rolebinding
  namespace: semantic-router-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: semantic-router-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: semantic-router-operator-controller-manager
  namespace: semantic-router-operator-system
