---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phi4-mini
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
#  storageClassName: default
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phi4-mini
  namespace: default
  labels:
    app: phi4-mini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phi4-mini
  template:
    metadata:
      labels:
        app: phi4-mini
    spec:
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: phi4-mini
      # vLLM needs to access the host's shared memory for tensor parallel inference.
      #      - name: shm
      #  emptyDir:
      #    medium: Memory
            #          sizeLimit: "2Gi"
      containers:
      - name: phi4-mini
        image: vllm/vllm-openai:latest
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve microsoft/Phi-4-mini-instruct --served-model-name phi4-mini microsoft/Phi-4-mini-instruct  --trust-remote-code --enable-chunked-prefill"
        ]
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
        ports:
        - containerPort: 8000
        resources:
          limits:
            #            cpu: "10"
            #            memory: 40G
            nvidia.com/gpu: "1"
          requests:
            #            cpu: "10"
            #            memory: 40Gi
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
            #        - name: shm
            #          mountPath: /dev/shm
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 600
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 600
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: phi4-mini
  namespace: default
spec:
  ports:
  - name: http-phi4-mini
    port: 80
    protocol: TCP
    targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: phi4-mini
  sessionAffinity: None
  type: ClusterIP

