apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: vllm-semantic-router
  namespace: vllm-semantic-router-system
  annotations:
    aigateway.envoyproxy.io/processing-body-mode: "buffered"
    aigateway.envoyproxy.io/allow-mode-override: "true"
spec:
  targetPorts:
    - number: 50051
  selector:
    matchLabels:
      app: vllm-semantic-router
  endpointPickerRef:
    name: semantic-router
    port:
      number: 50051
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: vllm-semantic-router
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: vllm-semantic-router
  namespace: vllm-semantic-router-system
spec:
  gatewayClassName: vllm-semantic-router
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vllm-semantic-router
  namespace: vllm-semantic-router-system
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: vllm-semantic-router
      namespace: vllm-semantic-router-system
  rules:
    - backendRefs:
        - group: inference.networking.k8s.io
          kind: InferencePool
          name: vllm-semantic-router
          namespace: vllm-semantic-router-system
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        request: 60s
